### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by RGlodAkshat** [cv-rits/LMSCNet#9]
Hello Everyone, 

First of all I thank you and commend you for all your hardwork in doing this.

The issue I encountered while trying to run the training script  using `python LMSCNet/train.py --cfg SSC_configs/examples/LMSCNet.yaml --dset_root <path/dataset/root>` 

I'm getting this Error

```
(lmscnet_ssc) rg_lord@AkshatPredator:~/Desktop/LMSCNet$ python LMSCNet/train.py --cfg SSC_configs/examples/LMSCNet.yaml --dset_root /home/rg_lord/Desktop/Alternate_hereDataset/semanticKITTI_v1.1_dscale
2024-03-06 22:42:42,112 -- ============ Training routine: "SSC_configs/examples/LMSCNet.yaml" ============

Traceback (most recent call last):
  File "LMSCNet/train.py", line 331, in <module>
    main()
  File "LMSCNet/train.py", line 302, in main
    dataset = get_dataset(_cfg)
  File "/home/rg_lord/Desktop/LMSCNet/LMSCNet/common/dataset.py", line 11, in get_dataset
    ds_test  = SemanticKITTI_dataloader(_cfg._dict['DATASET'], 'test')
  File "/home/rg_lord/Desktop/LMSCNet/LMSCNet/data/SemanticKITTI.py", line 47, in __init__
    self.get_filepaths(modality)
  File "/home/rg_lord/Desktop/LMSCNet/LMSCNet/data/SemanticKITTI.py", line 61, in get_filepaths
    sequences = list(sorted(glob(os.path.join(self.root_dir, 'dataset', 'sequences', '*')))[i] for i in self.split[self.phase])
  File "/home/rg_lord/Desktop/LMSCNet/LMSCNet/data/SemanticKITTI.py", line 61, in <genexpr>
    sequences = list(sorted(glob(os.path.join(self.root_dir, 'dataset', 'sequences', '*')))[i] for i in self.split[self.phase])
IndexError: list index out of range
```

I'm using v1.1 of the dataset which could be downloaded directly and whose sequence folder had 10 files. If anyone could help me then I would be glad as I'm a beginner in all these things.

**Comment by fengyxz** [comment]
Same question. Could you please tell me how to solve it? Tkx!!
